#docker compose for discord bot

#discord bot
services:
  discord-bot:
    image: ##name
    conntainer_name: discord-bot
    restart: always
    environment:
        DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
        






  #Maria DB
