name: Docker Build 

# Docker Build Workflow for Branch -> test_branch

on: 
  push: 
    branches: ["test-branch"]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
  #Check out the current repository
      - name: Checkout Code
        uses: actions/checkout@v4
  #Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
  #build Docker Image
      - name: Build the Docker image
        run: docker build -t theboarde/schankwirt:newest .
  #push Image to Docker Hub
      - name: Push to Docker Hub
        run: docker push theboarde/schankwirt:newest
      
